# Generated by Django 4.2.6 on 2023-11-10 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_date_joined"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
