# Generated by Django 4.2.6 on 2023-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeshop", "0004_alter_datawarehouse_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datawarehouse",
            name="customer_id",
            field=models.IntegerField(default=91, editable=False),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="customer_id",
            field=models.IntegerField(default=53, editable=False),
        ),
    ]
