# Generated by Django 4.2.6 on 2023-11-15 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeshop", "0007_alter_datawarehouse_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datawarehouse",
            name="customer_id",
            field=models.IntegerField(default=15, editable=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="line_item_amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="orders",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="unit_price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="customer_id",
            field=models.IntegerField(default=8, editable=False),
        ),
    ]
