# Generated by Django 4.2.6 on 2023-11-27 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0012_alter_orders_order_alter_orders_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_time', models.TimeField(default=django.utils.timezone.now, editable=False)),
                ('customer_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('line_item_amount', models.FloatField(editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.products')),
            ],
            options={
                'verbose_name_plural': 'Archives',
            },
        ),
    ]
