# Generated by Django 4.1 on 2023-10-26 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("product_group", models.CharField(max_length=20)),
                ("product_category", models.CharField(max_length=20)),
                ("product_type", models.CharField(max_length=40)),
                ("product", models.CharField(max_length=40)),
                ("product_description", models.CharField(max_length=100)),
                ("unit_of_measure", models.CharField(max_length=10)),
                ("current_retail_price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Receipts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.IntegerField()),
                ("transaction_date", models.DateField()),
                (
                    "transaction_time",
                    models.TimeField(default=django.utils.timezone.now),
                ),
                ("sales_outlet_id", models.IntegerField()),
                ("staff_id", models.IntegerField()),
                ("customer_id", models.IntegerField()),
                ("instore_yn", models.CharField(max_length=1)),
                ("order", models.IntegerField()),
                ("line_item_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("line_item_amount", models.FloatField()),
                ("unit_price", models.FloatField()),
            ],
        ),
    ]
