# Generated by Django 4.2.6 on 2023-10-27 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receipts",
            options={"verbose_name_plural": "Receipts"},
        ),
        migrations.RemoveField(
            model_name="receipts",
            name="instore_yn",
        ),
        migrations.RemoveField(
            model_name="receipts",
            name="sales_outlet_id",
        ),
        migrations.RemoveField(
            model_name="receipts",
            name="staff_id",
        ),
    ]
