# Generated by Django 4.2.6 on 2023-10-28 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "coffeeshop",
            "0002_alter_receipts_options_remove_receipts_instore_yn_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipts",
            name="line_item_amount",
        ),
        migrations.RemoveField(
            model_name="receipts",
            name="line_item_id",
        ),
        migrations.AlterField(
            model_name="receipts",
            name="customer_id",
            field=models.IntegerField(default=100, editable=False),
        ),
        migrations.AlterField(
            model_name="receipts",
            name="order",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="receipts",
            name="transaction_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="receipts",
            name="transaction_id",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="receipts",
            name="transaction_time",
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
