# Generated by Django 4.2.6 on 2023-10-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeshop", "0003_remove_receipts_line_item_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipts",
            name="line_item_amount",
            field=models.FloatField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
