# Generated by Django 4.2.6 on 2023-11-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeshop", "0009_alter_datawarehouse_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datawarehouse",
            name="customer_id",
            field=models.IntegerField(default=11, editable=False),
        ),
        migrations.AlterField(
            model_name="rawdata",
            name="customer_id",
            field=models.IntegerField(default=20, editable=False),
        ),
    ]
